apiVersion: v1
kind: Secret
metadata:
  name: steambot-secrets
  namespace: steambot
type: Opaque
stringData:
  DB_PASSWORD: "SteamBot_DB_2026!"
  JWT_SECRET: "$(([System.Convert]::ToBase64String([System.Security.Cryptography.RandomNumberGenerator]::GetBytes(32))))"
  ADMIN_PASSWORD: "Admin_SteamBot_2026!"
  STRIPE_SECRET_KEY: ""
  STRIPE_WEBHOOK_SECRET: ""
  SMTP_HOST: "smtp.spaceweb.ru"
  SMTP_USER: "steambot@communityrig.ru"
  SMTP_PASS: "1276908Ska"
