apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"postgres-pvc","namespace":"steambot"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"10Gi"}},"storageClassName":"local-path"}}
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
      volume.kubernetes.io/selected-node: worker-192.168.0.6
      volume.kubernetes.io/storage-provisioner: rancher.io/local-path
    creationTimestamp: "2026-02-25T11:37:27Z"
    finalizers:
    - kubernetes.io/pvc-protection
    name: postgres-pvc
    namespace: steambot
    resourceVersion: "1974"
    uid: 37414368-3edc-484b-a610-b2c1c57831eb
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
    storageClassName: local-path
    volumeMode: Filesystem
    volumeName: pvc-37414368-3edc-484b-a610-b2c1c57831eb
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 10Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"steambot-data-pvc","namespace":"steambot"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"5Gi"}},"storageClassName":"local-path"}}
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
      volume.kubernetes.io/selected-node: worker-192.168.0.5
      volume.kubernetes.io/storage-provisioner: rancher.io/local-path
    creationTimestamp: "2026-02-25T11:51:10Z"
    finalizers:
    - kubernetes.io/pvc-protection
    name: steambot-data-pvc
    namespace: steambot
    resourceVersion: "4983"
    uid: 8362fc53-e575-4dfa-a9c5-7fd835bfb4c4
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
    storageClassName: local-path
    volumeMode: Filesystem
    volumeName: pvc-8362fc53-e575-4dfa-a9c5-7fd835bfb4c4
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 5Gi
    phase: Bound
kind: List
metadata:
  resourceVersion: ""
